// Generated by refresh-members.mjs. Do not add private profile fields.
const raidCreditsSnapshot = {
  "schemaVersion": 1,
  "collection": "profiles",
  "source": "https://portal.raidguild.org/api/profiles",
  "capturedAt": "2026-09-17T17:08:44.841Z",
  "total": 158,
  "fields": [
    "id",
    "displayName",
    "handle"
  ],
  "members": [
    {
      "id": 97,
      "displayName": "🐙Musashi13#5579",
      "handle": "https-github-com-musashi13"
    },
    {
      "id": 3,
      "displayName": "$uns",
      "handle": "sunsakis"
    },
    {
      "id": 4,
      "displayName": "Aaron Bendersky",
      "handle": "chair28980"
    },
    {
      "id": 5,
      "displayName": "Aaron Foster",
      "handle": "pythonpete32"
    },
    {
      "id": 6,
      "displayName": "Aaron Osterby",
      "handle": "osterby"
    },
    {
      "id": 7,
      "displayName": "Aaron Soskin",
      "handle": "amsos"
    },
    {
      "id": 8,
      "displayName": "Adam Kerpelman",
      "handle": "thekerp"
    },
    {
      "id": 9,
      "displayName": "Aidan Musnitzky",
      "handle": "musnit"
    },
    {
      "id": 155,
      "displayName": "AlecM",
      "handle": "AlecM"
    },
    {
      "id": 11,
      "displayName": "Alex Hoff",
      "handle": "ajhoff"
    },
    {
      "id": 10,
      "displayName": "Alexander Keating",
      "handle": "alexkeating"
    },
    {
      "id": 152,
      "displayName": "Ali",
      "handle": "ali_alizadeh"
    },
    {
      "id": 158,
      "displayName": "amay",
      "handle": "amay1102"
    },
    {
      "id": 12,
      "displayName": "Amos Goh",
      "handle": "amosgoh"
    },
    {
      "id": 148,
      "displayName": "andrea",
      "handle": "PumpkingWok"
    },
    {
      "id": 13,
      "displayName": "ApeironCreations",
      "handle": "apeironcreations"
    },
    {
      "id": 163,
      "displayName": "Arnab",
      "handle": "dehatapocalypse"
    },
    {
      "id": 16,
      "displayName": "Ben.oxmo",
      "handle": "benoxmo"
    },
    {
      "id": 14,
      "displayName": "Benedictus Biedermayer",
      "handle": "benedictvs"
    },
    {
      "id": 15,
      "displayName": "Bennisan",
      "handle": "bennisan86"
    },
    {
      "id": 17,
      "displayName": "Beyondr",
      "handle": "thebeyondr"
    },
    {
      "id": 18,
      "displayName": "bingo the designer",
      "handle": "registerbiscuit-7919"
    },
    {
      "id": 19,
      "displayName": "Brandon Pao",
      "handle": "bcpao"
    },
    {
      "id": 20,
      "displayName": "Brian Rossetti",
      "handle": "brossetti1"
    },
    {
      "id": 21,
      "displayName": "Bruce Kroeze",
      "handle": "bkroeze"
    },
    {
      "id": 22,
      "displayName": "Callum Gladstone",
      "handle": "axia-callum"
    },
    {
      "id": 23,
      "displayName": "Carl Farterson",
      "handle": "carlfarterson"
    },
    {
      "id": 24,
      "displayName": "Chiali Tsai",
      "handle": "chialitsai"
    },
    {
      "id": 25,
      "displayName": "Christina, BorrowLucid",
      "handle": "3036"
    },
    {
      "id": 26,
      "displayName": "Coffee-Crusher",
      "handle": "n-a"
    },
    {
      "id": 27,
      "displayName": "Cooper Turley",
      "handle": "coopahtroopanew"
    },
    {
      "id": 28,
      "displayName": "Cristopher Ortega",
      "handle": "crisog"
    },
    {
      "id": 29,
      "displayName": "cupojoseph",
      "handle": "jschiarizzi"
    },
    {
      "id": 30,
      "displayName": "dan13ram",
      "handle": "dan13ram"
    },
    {
      "id": 31,
      "displayName": "DAO Jones",
      "handle": "tropical-wilson"
    },
    {
      "id": 32,
      "displayName": "Dapplion",
      "handle": "dapplion"
    },
    {
      "id": 33,
      "displayName": "Darren Mills",
      "handle": "darrenrm"
    },
    {
      "id": 170,
      "displayName": "David Dada",
      "handle": "daveproxy80"
    },
    {
      "id": 34,
      "displayName": "David Nellis",
      "handle": "dnellis74"
    },
    {
      "id": 35,
      "displayName": "degeneroach",
      "handle": "degeneroach"
    },
    {
      "id": 36,
      "displayName": "Dekan",
      "handle": "duckanbro"
    },
    {
      "id": 37,
      "displayName": "Derrek",
      "handle": "derrekcoleman"
    },
    {
      "id": 38,
      "displayName": "Drew Harding",
      "handle": "burningfiat"
    },
    {
      "id": 39,
      "displayName": "dtolsen",
      "handle": "dtolsen"
    },
    {
      "id": 45,
      "displayName": "E-ratic",
      "handle": "eye-ults"
    },
    {
      "id": 40,
      "displayName": "earth2travis",
      "handle": "earth2travis"
    },
    {
      "id": 41,
      "displayName": "Ed Zynda",
      "handle": "ezynda3"
    },
    {
      "id": 42,
      "displayName": "Elco",
      "handle": "elementcomplex"
    },
    {
      "id": 43,
      "displayName": "Elijah befitsandpiper",
      "handle": "befitsandpiper"
    },
    {
      "id": 44,
      "displayName": "Elliott Conway",
      "handle": "ecwireless"
    },
    {
      "id": 46,
      "displayName": "Eric Arsenault",
      "handle": "eric_rsno"
    },
    {
      "id": 47,
      "displayName": "Garett \"Kinchasa\" Laugavitz",
      "handle": "kinchasa"
    },
    {
      "id": 48,
      "displayName": "Gaye \"Gaia\"",
      "handle": "gaye-soykok"
    },
    {
      "id": 164,
      "displayName": "GB-53f8",
      "handle": "GaurangBrdv"
    },
    {
      "id": 49,
      "displayName": "georgeh",
      "handle": "geovgy"
    },
    {
      "id": 50,
      "displayName": "Guillaume Palayer",
      "handle": "guillaumepalayer"
    },
    {
      "id": 51,
      "displayName": "Gus",
      "handle": "kisgus"
    },
    {
      "id": 52,
      "displayName": "Hammad Jutt",
      "handle": "meta_dreamer"
    },
    {
      "id": 53,
      "displayName": "HanValen",
      "handle": "mackbowes"
    },
    {
      "id": 54,
      "displayName": "Harsh Maur",
      "handle": "harshmaur"
    },
    {
      "id": 55,
      "displayName": "HHH",
      "handle": "hhh-gh"
    },
    {
      "id": 56,
      "displayName": "Hunter (daopunk)",
      "handle": "daopunk"
    },
    {
      "id": 57,
      "displayName": "Isaac Patka",
      "handle": "ipatka"
    },
    {
      "id": 58,
      "displayName": "Jaclyn Lenee Junger",
      "handle": "jaclynlenee"
    },
    {
      "id": 59,
      "displayName": "Jacob Homanics",
      "handle": "jacobhomanics"
    },
    {
      "id": 60,
      "displayName": "James Duncan",
      "handle": "okduncan"
    },
    {
      "id": 61,
      "displayName": "James Young",
      "handle": "jamesyoung"
    },
    {
      "id": 62,
      "displayName": "jarryingnaut",
      "handle": "growindiedev"
    },
    {
      "id": 63,
      "displayName": "Jeff Krantz",
      "handle": "ztnark"
    },
    {
      "id": 64,
      "displayName": "Jip Stavenuiter",
      "handle": "jipperism"
    },
    {
      "id": 66,
      "displayName": "John (launchninja)",
      "handle": "launchninja"
    },
    {
      "id": 67,
      "displayName": "Jonathan Dunlap",
      "handle": "jadbox"
    },
    {
      "id": 68,
      "displayName": "Jordan",
      "handle": "jordanlovesred-9467"
    },
    {
      "id": 69,
      "displayName": "Jordan Greenberg",
      "handle": "jordang7"
    },
    {
      "id": 70,
      "displayName": "Jordan Lesich",
      "handle": "jordanlesich"
    },
    {
      "id": 71,
      "displayName": "joshsdoug",
      "handle": "joshsdoug"
    },
    {
      "id": 72,
      "displayName": "Joshua Lapidus",
      "handle": "joshuasl"
    },
    {
      "id": 160,
      "displayName": "JOYBOY",
      "handle": "ME"
    },
    {
      "id": 73,
      "displayName": "jp",
      "handle": "jonathanprozzi"
    },
    {
      "id": 74,
      "displayName": "Kames Geraghty",
      "handle": "kamescg"
    },
    {
      "id": 75,
      "displayName": "Ken Beckers",
      "handle": "bitbeckers"
    },
    {
      "id": 76,
      "displayName": "Kevin Monahan",
      "handle": "kevinmonahan"
    },
    {
      "id": 77,
      "displayName": "Kevin Siegler",
      "handle": "topocount"
    },
    {
      "id": 78,
      "displayName": "Kirch",
      "handle": "n-a-2"
    },
    {
      "id": 79,
      "displayName": "Konrad Gnat",
      "handle": "https-github-com-kon-rad"
    },
    {
      "id": 80,
      "displayName": "Kyle Stargarden",
      "handle": "st4rgarden"
    },
    {
      "id": 81,
      "displayName": "Lahcen KHADDAOUI",
      "handle": "l-kh"
    },
    {
      "id": 82,
      "displayName": "Lili Feyerabend",
      "handle": "lililashka"
    },
    {
      "id": 83,
      "displayName": "Loren Speer",
      "handle": "lolo-9084"
    },
    {
      "id": 87,
      "displayName": "Lou",
      "handle": "louchi"
    },
    {
      "id": 84,
      "displayName": "Louis Giraux",
      "handle": "louisgrx"
    },
    {
      "id": 85,
      "displayName": "Lucas Campbell",
      "handle": "0xlucas-3124"
    },
    {
      "id": 86,
      "displayName": "Lucas Cerro",
      "handle": "lucascerro"
    },
    {
      "id": 88,
      "displayName": "Luke Kim",
      "handle": "n-a-3"
    },
    {
      "id": 89,
      "displayName": "Luxumbra.eth",
      "handle": "luxumbra"
    },
    {
      "id": 90,
      "displayName": "Manuel Fernandez",
      "handle": "manu"
    },
    {
      "id": 91,
      "displayName": "Marco (mprime)",
      "handle": "mprimi"
    },
    {
      "id": 93,
      "displayName": "Mark Pascall",
      "handle": "mark_pascall"
    },
    {
      "id": 92,
      "displayName": "Marko Prljic",
      "handle": "markoprljic"
    },
    {
      "id": 156,
      "displayName": "martin",
      "handle": "Benzima"
    },
    {
      "id": 94,
      "displayName": "Matthew Carano",
      "handle": "matthewcarano"
    },
    {
      "id": 95,
      "displayName": "Matthew O'Connell",
      "handle": "moconnell"
    },
    {
      "id": 173,
      "displayName": "matthu",
      "handle": "matthu"
    },
    {
      "id": 65,
      "displayName": "mkdir",
      "handle": "themkdir"
    },
    {
      "id": 149,
      "displayName": "Moors",
      "handle": "orugaagii"
    },
    {
      "id": 96,
      "displayName": "Mr Deadce11",
      "handle": "https-github-com-mrdeadce11"
    },
    {
      "id": 98,
      "displayName": "Nick Rishwain",
      "handle": "nickjrishwain"
    },
    {
      "id": 99,
      "displayName": "nintynick",
      "handle": "nintynick-4570"
    },
    {
      "id": 100,
      "displayName": "nitegeist",
      "handle": "nitegeist"
    },
    {
      "id": 101,
      "displayName": "Omni Analytics Group (Lawrence Mosley, Yogesh Bansal, and Eric Hare)",
      "handle": "https-github-com-omni-analytics-group"
    },
    {
      "id": 102,
      "displayName": "Patrick Gallagher",
      "handle": "pi0neerpat"
    },
    {
      "id": 103,
      "displayName": "Penguin",
      "handle": "c0mput3rxz"
    },
    {
      "id": 104,
      "displayName": "Peter (pmp)",
      "handle": "petermphillips"
    },
    {
      "id": 105,
      "displayName": "peth",
      "handle": "peth-yursick"
    },
    {
      "id": 106,
      "displayName": "plor",
      "handle": "plor"
    },
    {
      "id": 107,
      "displayName": "Polina Aladina",
      "handle": "polycarpik"
    },
    {
      "id": 108,
      "displayName": "pupcakes",
      "handle": "fluffy9"
    },
    {
      "id": 169,
      "displayName": "Queen Raida",
      "handle": "queen-raida"
    },
    {
      "id": 109,
      "displayName": "Rahul S",
      "handle": "rhlstrm"
    },
    {
      "id": 110,
      "displayName": "Ross Campbell",
      "handle": "ro5s"
    },
    {
      "id": 111,
      "displayName": "Rowdy",
      "handle": "0xrowdy"
    },
    {
      "id": 112,
      "displayName": "Ryan (Autocrat)",
      "handle": "ryansea"
    },
    {
      "id": 113,
      "displayName": "Saimano",
      "handle": "manolingam"
    },
    {
      "id": 115,
      "displayName": "Samuel Baurle",
      "handle": "burleebau"
    },
    {
      "id": 116,
      "displayName": "Santiago",
      "handle": "santteegt"
    },
    {
      "id": 117,
      "displayName": "Sascha",
      "handle": "smombartz"
    },
    {
      "id": 118,
      "displayName": "Sasquatch",
      "handle": "sasquatchtru"
    },
    {
      "id": 119,
      "displayName": "sayonara",
      "handle": "wtfsayo"
    },
    {
      "id": 120,
      "displayName": "Scottrepreneur",
      "handle": "scottrepreneur"
    },
    {
      "id": 121,
      "displayName": "Sergey Ukustov",
      "handle": "ukstv"
    },
    {
      "id": 122,
      "displayName": "Sero",
      "handle": "seroxdesign"
    },
    {
      "id": 165,
      "displayName": "Silver",
      "handle": "Silverwinss"
    },
    {
      "id": 123,
      "displayName": "Simona Pop",
      "handle": "simona-pop"
    },
    {
      "id": 114,
      "displayName": "skuhl",
      "handle": "skuhlmann"
    },
    {
      "id": 124,
      "displayName": "Sourav Kumar Nanda",
      "handle": "sourav-kumar-nanda"
    },
    {
      "id": 171,
      "displayName": "sparklin",
      "handle": "Dr"
    },
    {
      "id": 125,
      "displayName": "Spencer Graham",
      "handle": "slgraham"
    },
    {
      "id": 126,
      "displayName": "Stephen Diesel",
      "handle": "stephenpdiesel"
    },
    {
      "id": 127,
      "displayName": "Suede",
      "handle": "suede0619"
    },
    {
      "id": 128,
      "displayName": "Sydney Lai",
      "handle": "sydneylai"
    },
    {
      "id": 129,
      "displayName": "taekekz",
      "handle": "takekz"
    },
    {
      "id": 130,
      "displayName": "Tarun Bansal",
      "handle": "tarunbhm"
    },
    {
      "id": 131,
      "displayName": "Tim Ultreia",
      "handle": "tkernell"
    },
    {
      "id": 132,
      "displayName": "Tolu",
      "handle": "tn-5913"
    },
    {
      "id": 133,
      "displayName": "Tom Eaton",
      "handle": "integral-studio"
    },
    {
      "id": 134,
      "displayName": "Tom French",
      "handle": "tomafrench"
    },
    {
      "id": 135,
      "displayName": "Tommy Cox",
      "handle": "proofoftom"
    },
    {
      "id": 136,
      "displayName": "Travis Wyche",
      "handle": "traviswyche"
    },
    {
      "id": 137,
      "displayName": "Tufnel_Enterprises",
      "handle": "psparacino"
    },
    {
      "id": 138,
      "displayName": "vani11a",
      "handle": "vani11aa"
    },
    {
      "id": 139,
      "displayName": "Ven Gist",
      "handle": "vengist"
    },
    {
      "id": 140,
      "displayName": "Victor (YKW)",
      "handle": "youngkidwarrior"
    },
    {
      "id": 141,
      "displayName": "vid",
      "handle": "vidvidvid"
    },
    {
      "id": 142,
      "displayName": "Will Griffith",
      "handle": "willdrogriff-9995"
    },
    {
      "id": 143,
      "displayName": "Will Krol-Sinclair",
      "handle": "damagedgoods-5437"
    },
    {
      "id": 144,
      "displayName": "Yalor",
      "handle": "yalormewn"
    },
    {
      "id": 145,
      "displayName": "Zach Herring",
      "handle": "zherring"
    },
    {
      "id": 146,
      "displayName": "Zefram Lou",
      "handle": "zeframl"
    }
  ]
};
window.RAID_CREDITS_SNAPSHOT = Object.freeze({
  ...raidCreditsSnapshot,
  members: Object.freeze(raidCreditsSnapshot.members.map((member) => Object.freeze(member))),
});
