import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const sourceURL = "https://portal.raidguild.org/api/profiles";
const pageSize = 100;
const members = [];
let expectedTotal = null;
let page = 1;
let totalPages = 1;

do {
  const url = new URL(sourceURL);
  url.searchParams.set("limit", String(pageSize));
  url.searchParams.set("page", String(page));
  url.searchParams.set("depth", "0");
  url.searchParams.set("sort", "displayName");
  url.searchParams.set("select[displayName]", "true");
  url.searchParams.set("select[handle]", "true");

  const response = await fetch(url, { headers: { Accept: "application/json" } });
  if (!response.ok) throw new Error(`Portal profiles request failed: ${response.status}`);

  const result = await response.json();
  if (!Array.isArray(result.docs)) throw new Error("Portal profiles response did not include docs");
  expectedTotal ??= result.totalDocs;
  totalPages = result.totalPages;
  members.push(
    ...result.docs.map(({ id, displayName, handle }) => ({
      id,
      displayName: String(displayName || "").trim(),
      handle: String(handle || "").trim(),
    })),
  );
  page += 1;
} while (page <= totalPages);

if (members.length !== expectedTotal) {
  throw new Error(`Expected ${expectedTotal} Portal profiles but received ${members.length}`);
}
if (members.some(({ id, displayName, handle }) => id == null || !displayName || !handle)) {
  throw new Error("Portal profile snapshot contains a missing id, display name, or handle");
}
if (new Set(members.map(({ id }) => String(id))).size !== members.length) {
  throw new Error("Portal profile snapshot contains duplicate ids");
}

members.sort((a, b) => a.displayName.localeCompare(b.displayName, "en", { sensitivity: "base" }));

const snapshot = {
  schemaVersion: 1,
  collection: "profiles",
  source: sourceURL,
  capturedAt: new Date().toISOString(),
  total: members.length,
  fields: ["id", "displayName", "handle"],
  members,
};
const serialized = JSON.stringify(snapshot, null, 2);
const output = `// Generated by refresh-members.mjs. Do not add private profile fields.\n` +
  `const raidCreditsSnapshot = ${serialized};\n` +
  `window.RAID_CREDITS_SNAPSHOT = Object.freeze({\n` +
  `  ...raidCreditsSnapshot,\n` +
  `  members: Object.freeze(raidCreditsSnapshot.members.map((member) => Object.freeze(member))),\n` +
  `});\n`;

await writeFile(fileURLToPath(new URL("members.js", import.meta.url)), output, "utf8");
console.log(`Captured ${members.length} Portal member profiles → members.js`);
