import type {HeroId,LevelId,SkillId,Checkpoint} from './raid-content.js';
export {RAID_VERSION,LEGACY_RAID_VERSION,LEVELS,CHECKPOINTS,HERO_IDS,STARTER_HERO_IDS,SKILLS,PERKS,perkFor,LAVA_BOSS_SCHEDULE,lavaBossSchedule} from './raid-content.js';
export type RaidProfile={schemaVersion:3;revision:number;unlocked:LevelId[];unlockedHeroes:HeroId[];checkpoints:Record<LevelId,Record<HeroId,string[]>>;milestones:Record<LevelId,Partial<Record<HeroId,boolean>>>;skills:Record<HeroId,Record<SkillId,number>>;perks:Record<HeroId,string[]>;equippedPerk:Record<HeroId,string|null>;realmMastery:Record<HeroId,LevelId[]>;classMastery:HeroId[];purchases:unknown[];equips:unknown[];monsters:Record<string,{encountered:number;kills:number;counterKills:number}>};
export type RaidRunConfig={version:'3';character:HeroId;level:LevelId;skills:Record<SkillId,number>;equippedPerk:string|null;target:Checkpoint|null};
export const MONSTERS_CHAIN_ID:number;
export const MONSTERS_CONTRACT:string;
export const MONSTERS:Record<string,{realm:'forest'|'desert'|'ice'|'lava';tokenId:number;name:string;size:string;alignment:string;actions:string;ability:string;weakness:string;locomotion:string;language:string}>;
export function emptyProfile():RaidProfile;
export function normalizeProfile(value:unknown):RaidProfile;
export function credits(profile:RaidProfile,hero:HeroId):number;
export function nextCheckpoint(profile:RaidProfile,hero:HeroId,level:LevelId):Checkpoint|null;
export function purchase(profile:RaidProfile,hero:HeroId,skill:SkillId,expectedRevision:number,rank?:number,requestId?:string):RaidProfile;
export function purchasePerk(profile:RaidProfile,hero:HeroId,perkId:string,expectedRevision:number,requestId:string):RaidProfile;
export function equipPerk(profile:RaidProfile,hero:HeroId,perkId:string|null,expectedRevision:number,requestId:string):RaidProfile;
export function monsterStage(record:unknown):number;
export function validateRunConfig(body:unknown,profile:RaidProfile):RaidRunConfig;
export function validateMonsterProgress(value:unknown,previous?:unknown):Record<string,{encountered:number;kills:number;counterKills:number}>;
export function applyProgress(profile:RaidProfile,config:RaidRunConfig|any,progress:any,previous?:any):{profile:RaidProfile;progress:any};
