import {test} from 'node:test';import assert from 'node:assert/strict';
import {freshGame,solution,launch,advance,upgrade,repair,capacity,parseSave,missions,canLaunch} from '../dist/game.js';
function fire(s,city,id){const a=solution(s,city);return launch(s,city,id,a.bearing,a.charge)}
function funded(s){s.power=capacity(s);s.material=500;s.supplies=500;return s}
test('freight return arrives after two subsequent shifts and save resumes',()=>{const s=freshGame();fire(s,'azure','freight');assert.equal(s.turn,2);assert.equal(s.shipments.length,1);const before=s.supplies;advance(s);assert.equal(s.shipments.length,1);advance(s);assert.equal(s.shipments.length,0);assert.equal(s.supplies,before+26);assert.deepEqual(parseSave(JSON.stringify(s)),s)});
test('blockade holds shuttles, breaking it releases overdue cargo',()=>{const s=funded(freshGame());s.turn=5;fire(s,'azure','freight');assert.equal(s.blockade,true);advance(s);advance(s);assert.equal(s.shipments.length,1);fire(funded(s),'azure','break-blockade');assert.equal(s.blockade,false);assert.equal(s.shipments.length,0)});
test('district destruction is permanent and does not erase deployed fleets',()=>{const s=funded(freshGame());s.blockade=true;for(let i=0;i<3;i++)fire(funded(s),'vesper','strike-shipyards');assert.equal(s.districts.shipyards,0);assert.equal(s.blockade,true);assert.ok(!missions(s,'vesper').some(x=>x.id==='strike-shipyards'));s.blockade=false;for(let i=0;i<10;i++)advance(s);assert.equal(s.blockade,false)});
test('diplomatic campaign can be completed with attainable resources',()=>{const s=freshGame();fire(s,'azure','freight');fire(s,'meridian','relief');fire(s,'meridian','relief');assert.equal(s.trust,2);fire(s,'vesper','demo');while(s.power<80)advance(s);fire(s,'vesper','strike-shipyards');while(s.power<80)advance(s);fire(s,'vesper','strike-command');while(s.power<1)advance(s);fire(s,'vesper','ultimatum');assert.equal(s.surrendered,true);assert.equal(s.won,true);assert.equal(s.blockade,false)});
test('military victory requires trade and both command and yards disabled',()=>{const s=funded(freshGame());s.levels.rail=1;fire(s,'azure','freight');for(const d of ['shipyards','command'])for(let i=0;i<2;i++)fire(funded(s),'vesper','heavy-'+d);if(s.blockade)fire(funded(s),'azure','break-blockade');assert.equal(s.won,true);assert.equal(s.surrendered,false)});
test('miss spends resources without receiving rewards',()=>{const s=freshGame(),before=s.material;const r=launch(s,'azure','freight',15,70);assert.equal(r.hit,false);assert.equal(s.deliveries,0);assert.equal(s.shipments.length,0);assert.ok(s.material<before)});
test('invalid launch, unknown mission and unaffordable construction do not mutate state',()=>{const s=freshGame();s.power=0;const before=JSON.stringify(s);assert.throws(()=>fire(s,'azure','freight'));assert.equal(JSON.stringify(s),before);assert.throws(()=>launch(s,'azure','bad',0,100));assert.equal(JSON.stringify(s),before);s.supplies=0;const b=JSON.stringify(s);assert.throws(()=>upgrade(s,'production'));assert.equal(JSON.stringify(s),b);assert.ok(canLaunch(s,'azure','freight',NaN,100))});
test('local production allows recovery from empty supplies and upgrades cap correctly',()=>{const s=funded(freshGame());upgrade(s,'production');s.supplies=0;advance(s);assert.equal(s.supplies,5);funded(s);for(let i=0;i<3;i++)upgrade(s,'battery');assert.equal(capacity(s),370);assert.throws(()=>upgrade(s,'battery'));s.raidDamage=1;repair(s);assert.equal(s.raidDamage,0)});
test('repeat demonstrations cannot postpone retaliation indefinitely',()=>{const s=funded(freshGame());fire(s,'vesper','demo');const due=s.nextThreat;fire(s,'vesper','demo');assert.equal(s.nextThreat,due);assert.equal(s.pressure,1)});
test('corrupt saves are rejected',()=>{assert.equal(parseSave('{bad'),null);const s=freshGame();s.levels.solar=100;assert.equal(parseSave(JSON.stringify(s)),null)});
