import {test} from 'node:test';import assert from 'node:assert/strict';
import {freshGame,launch,advance,upgrade,repair,capacity,parseSave,missions,canLaunch,prediction,missionCost} from '../dist/game.js';
import {SYSTEM,bodies,flightShifts,targetSpec} from '../dist/orbital.js';
// Test-only construction of a launch window. There is no automatic solution in the game UI.
function aim(s,city,id){const bearing=-50,speed=3.2,p=prediction(s,city,id,bearing,speed,0);const phase=((p.impactAngle-p.targetArrival)%(2*Math.PI)+2*Math.PI)%(2*Math.PI);return {bearing,speed,departure:phase/(SYSTEM.spin-bodies(0).omega)/3600}}
function fire(s,city,id){const a=aim(s,city,id);return launch(s,city,id,a.bearing,a.speed,a.departure)}
function funded(s){s.power=capacity(s);s.material=500;s.supplies=500;return s}
test('preview and actual freight outcome agree; return arrives two subsequent shifts later',()=>{const s=freshGame(),a=aim(s,'azure','freight'),p=prediction(s,'azure','freight',a.bearing,a.speed,a.departure);assert.equal(p.hit,true);const r=launch(s,'azure','freight',a.bearing,a.speed,a.departure);assert.deepEqual(r.flight,p);assert.equal(s.turn,1+flightShifts(p,a.departure));assert.equal(s.shipments.length,1);s.nextThreat=99;const before=s.supplies;advance(s);assert.equal(s.shipments.length,1);advance(s);assert.equal(s.shipments.length,0);assert.equal(s.supplies,before+26);assert.deepEqual(parseSave(JSON.stringify(s)),s)});
test('blockade holds shuttles; destroying its anchorage releases cargo',()=>{const s=funded(freshGame());s.blockade=true;s.nextThreat=99;fire(s,'azure','freight');advance(s);advance(s);assert.equal(s.shipments.length,1);fire(funded(s),'azure','break-blockade');assert.equal(s.blockade,false);advance(s);assert.equal(s.shipments.length,0)});
test('district destruction stops future operations but not deployed fleets',()=>{const s=funded(freshGame());s.blockade=true;for(let i=0;i<3;i++)fire(funded(s),'vesper','strike-shipyards');assert.equal(s.districts.shipyards,0);assert.equal(s.blockade,true);assert.ok(!missions(s,'vesper').some(x=>x.id==='strike-shipyards'));s.blockade=false;for(let i=0;i<10;i++)advance(s);assert.equal(s.blockade,false)});
test('diplomatic campaign remains achievable without injecting resources',()=>{const s=freshGame();fire(s,'azure','freight');fire(s,'meridian','relief');fire(s,'meridian','relief');assert.equal(s.trust,2);for(const id of ['demo','strike-shipyards','strike-command']){while(s.power<65)advance(s);assert.equal(fire(s,'vesper',id).hit,true)}fire(s,'vesper','ultimatum');assert.equal(s.won,true);assert.equal(s.surrendered,true)});
test('military victory requires trade, command and yards destroyed, and no blockade',()=>{const s=funded(freshGame());s.levels.rail=1;fire(s,'azure','freight');for(const d of ['shipyards','command'])for(let i=0;i<2;i++)fire(funded(s),'vesper','heavy-'+d);if(s.blockade)fire(funded(s),'azure','break-blockade');assert.equal(s.won,true);assert.equal(s.surrendered,false)});
test('failed orbit spends launch resources but cannot deal damage or grant cargo',()=>{const s=freshGame(),r=launch(s,'vesper','strike-command',0,1.6);assert.equal(r.hit,false);assert.equal(r.flight.outcome,'moon');assert.equal(s.districts.command,100);assert.equal(s.pressure,0);assert.equal(s.shipments.length,0);assert.equal(s.lastShot.outcome,'moon')});
test('invalid settings and unaffordable construction leave state intact',()=>{const s=freshGame();s.power=0;let before=JSON.stringify(s);assert.throws(()=>fire(s,'azure','freight'));assert.throws(()=>launch(s,'azure','bad',0,3));assert.throws(()=>launch(s,'azure','freight',NaN,3));assert.throws(()=>launch(s,'azure','freight',-50,3,25));assert.equal(JSON.stringify(s),before);s.supplies=0;before=JSON.stringify(s);assert.throws(()=>upgrade(s,'production'));assert.equal(JSON.stringify(s),before)});
test('production recovers empty supplies; upgrades, repairs and speed cost remain meaningful',()=>{const s=funded(freshGame());upgrade(s,'production');s.supplies=0;advance(s);assert.equal(s.supplies,5);funded(s);for(let i=0;i<3;i++)upgrade(s,'battery');assert.equal(capacity(s),370);assert.throws(()=>upgrade(s,'battery'));s.raidDamage=1;repair(s);assert.equal(s.raidDamage,0);const m=missions(s,'azure')[0];assert.equal(missionCost(m,3.2).power,m.power);assert.equal(missionCost(m,6.4).power,m.power*4)});
test('repeated demonstration cannot repeatedly delay retaliation',()=>{const s=funded(freshGame());s.nextThreat=99;fire(s,'vesper','demo');const due=s.nextThreat;fire(funded(s),'vesper','demo');assert.equal(s.nextThreat,due);assert.equal(s.pressure,1)});
test('old saves load without erasing progress; corrupt trajectory and clock rejected',()=>{const s=freshGame();s.deliveries=2;delete s.clock;assert.equal(parseSave(JSON.stringify(s)).deliveries,2);s.clock=-1;assert.equal(parseSave(JSON.stringify(s)),null);delete s.clock;s.lastShot={trail:[{x:null,y:0,t:1}]};assert.equal(parseSave(JSON.stringify(s)).lastShot,null);assert.equal(parseSave('{bad'),null)});
test('waiting for departure advances mobilization; plotting has no side effects',()=>{const s=freshGame(),before=JSON.stringify(s),p=prediction(s,'azure','freight',-50,3.2,24);assert.equal(JSON.stringify(s),before);launch(s,'azure','freight',-50,3.2,24);assert.equal(s.turn,1+flightShifts(p,24));assert.ok(s.log.some(x=>x.title==='Azure is blockaded.'))});
