import assert from 'node:assert/strict';
import {Atmosphere} from '../dist/atmosphere.js';
const nodes=[];const param=()=>({value:0,setTargetAtTime(v){assert.ok(Number.isFinite(v));this.value=v},setValueAtTime(v){this.value=v},linearRampToValueAtTime(v){this.value=v},exponentialRampToValueAtTime(v){assert.ok(v>0);this.value=v}});
const node=()=>{const n={gain:param(),frequency:param(),Q:param(),pan:param(),connect(){},disconnect(){this.disconnected=true},start(){},stop(){this.stopped=true}};nodes.push(n);return n};
const c={currentTime:0,sampleRate:8000,createBuffer:()=>({getChannelData:()=>new Float32Array(32000)}),createBufferSource:node,createGain:node,createBiquadFilter:node,createOscillator:node,createStereoPanner:node};
const a=new Atmosphere(c,node());const initial=nodes.length;
a.update({stage:5,anomaly:30,depth:3,index:1,time:4,active:false});assert.equal(nodes.length,initial);assert.equal(a.air.gain.value,0);
c.currentTime=10;a.update({stage:5,anomaly:30,depth:3,index:1,time:10,active:true});assert.ok(nodes.length>initial);const after=nodes.length;a.impact();assert.equal(nodes.length,after,'Impact cooldown');
for(const n of nodes.filter(n=>n.stopped))n.onended();assert.ok(nodes.slice(initial).every(n=>n.disconnected),'Finished impacts release every node');
console.log('PASS: muted atmosphere, finite levels, irregular impacts, cooldown and node cleanup.');
const {wallMusicMix}=await import('../dist/atmosphere.js');
const model={offset:{x:12},worldZ:i=>-42-i*64,chunks:new Map([[1,{room:{kind:'chairs',w:10}}]])};
const near=wallMusicMix(model,{x:16,z:-105},0),far=wallMusicMix(model,{x:0,z:-105},0),turned=wallMusicMix(model,{x:16,z:-105},Math.PI);
assert.ok(near.gain>.6&&near.gain<.8);assert.equal(far.gain,0);assert.ok(near.pan>0&&turned.pan<0);assert.ok(near.cutoff>3000&&near.cutoff<4500);
assert.equal(wallMusicMix(null,{x:0,z:0},0).gain,0);
console.log('PASS: wall music fades by distance, follows head direction, respects world offsets and stays muffled.');
const nurseryModel={offset:{x:0},worldZ:i=>-i*64,chunks:new Map([[8,{room:{kind:'nursery',w:10}}]])},position={x:2,z:-511};
assert.ok(wallMusicMix(nurseryModel,position,0,'nursery').gain>.4);
assert.equal(wallMusicMix(nurseryModel,position,0,'office').gain,0,'Nursery never uses office track');
assert.equal(wallMusicMix(model,{x:16,z:-105},0,'nursery').gain,0,'Office never uses nursery track');
assert.equal(wallMusicMix(nurseryModel,{x:2,z:-490},0,'nursery').gain,0,'Nursery fades out beyond the room');
const originalAudio=globalThis.Audio;
globalThis.Audio=class{constructor(src){this.src=src;this.paused=true;}play(){this.paused=false;return Promise.resolve();}pause(){this.paused=true;}};
c.createMediaElementSource=node;a.initMusic();assert.equal(a.musicLayers.length,2);assert.ok(a.musicLayers[1].music.src.endsWith('nursery-doom.mp3'));assert.equal(a.musicLayers[1].music.loop,true);
a.setMusicActive(true);await Promise.resolve();assert.ok(a.musicLayers.every(l=>!l.music.paused));
a.update({stage:7,anomaly:53,depth:8,index:8,time:12,active:true,model:nurseryModel,player:position});assert.equal(a.musicLayers[0].gain.gain.value,0);assert.ok(a.musicLayers[1].gain.gain.value>.4);
a.setMusicActive(false);a.update({stage:7,anomaly:53,depth:8,index:8,time:13,active:false,model:nurseryModel,player:position});assert.ok(a.musicLayers.every(l=>l.music.paused&&l.gain.gain.value===0));
globalThis.Audio=originalAudio;
console.log('PASS: correct nursery track, room-specific mixing, looping, distance fade and shared mute/pause.');
const {positionClunk}=await import('../dist/atmosphere.js');
c.createPanner=()=>Object.assign(node(),{positionX:param(),positionY:param(),positionZ:param()});
c.currentTime=30;a.lastImpact=29;const beforeCue=nodes.length;
a.impact({source:{x:0,z:20},player:{x:0,z:0},yaw:0});
const cue=a.rearCue;assert.equal(cue.pan.panningModel,'HRTF');assert.ok(cue.pan.positionZ.value>0,'Source starts behind listener');
a.update({stage:5,anomaly:30,depth:3,index:1,time:30,active:true,player:{x:0,z:0},yaw:Math.PI});
assert.ok(cue.pan.positionZ.value<0,'Turning around places fixed sound ahead');assert.equal(cue.level.gain.value,.32);
a.update({stage:5,anomaly:30,depth:3,index:1,time:30,active:false,player:{x:0,z:0},yaw:0});assert.equal(cue.level.gain.value,0,'Pause silences cue');
for(const n of nodes.slice(beforeCue).filter(n=>n.stopped))n.onended();assert.equal(a.rearCue,null);assert.ok(nodes.slice(beforeCue).every(n=>n.disconnected));
console.log('PASS: quiet rear HRTF clunk tracks turn, mutes and releases nodes.');
